[package]
name = "rust_calc"
version = "0.1.1"
authors = ["elipmoc <relipmoc101@gmail.com>", "ay65535 <ay65535@icloud.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5"
